### ISSUE TITLE
iPhone users can't connect 

### ISSUE THREAD

**Issue by cazure-n00b** [atakhq/takserver-deb-installer#2]
using the script which works splendid. only iPhone users can't connect.
using this on a VPS & takserver_4.9-RELEASE9_all.deb

**Comment by atakhq** [comment]
Are you using a FQDN? ITAK requires a secure tls connection.

**Comment by cazure-n00b** [comment]
Yes, I've been using FQDN and it's all set up splendidly. Everything worked out great in 4.8 but in 4.9 these issues arise.

**Comment by atakhq** [comment]
This has been fixed, please pull latest version of script and use that.

**Comment by cazure-n00b** [comment]
Use the script again to update the server with a new version? 
Is there a simple "upgrade" version of this script?

**Comment by atakhq** [comment]
The build script itself is fine, the part that generated the QR code on screen was hardcoding the wrong strings in the QR string. You can manually enter the server details in ITAK and it will work. Can also steal the line from the script that generates the QR and put the correct values in for your server and it will generate proper QR for you.

**Comment by cazure-n00b** [comment]
Users failed to connect also when manually typing it in. I did a re-install of version 4.8.x instead of 4.9.x. In 4.8.x, even with running the old script, works everything splendidly
